Smart Workspace Server/force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Smart Workspace Server/force-app/main/default/objects/Sensor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sensors</relationshipLabel>
    <relationshipName>Sensors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Smart Workspace Server/force-app/main/default/classes/SensorRepository.cls
public with sharing class SensorRepository {
    public SensorRepository() {
    }

    public Sensor__c findSensorByIdAndAccount(String sensorId, String accountId) {
        List<Sensor__c> sensors = [SELECT Name FROM Sensor__c WHERE Name =: sensorId
                                                                    AND Account__c =: accountId LIMIT 1];
        if(sensors.size() == 0) {
            return null;
        }
        return sensors[0];
    }

    public Sensor__c createSensor(String name, String accountId) {
        Sensor__c sensor = new Sensor__c(Name = name,
                                         Account__c = accountId);
        insert sensor;
        return sensor;
    }
}