Smart Workspace Server/force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Smart Workspace Server/force-app/main/default/objects/Sensor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sensors</relationshipLabel>
    <relationshipName>Sensors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Smart Workspace Server/force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Smart Workspace Server/force-app/main/default/classes/SensorRestServiceTest.cls
@IsTest
public with sharing class SensorRestServiceTest {

    public static String SERVER_BASE_URL = 'https://resilient-koala-ulbvbp-dev-ed.my.salesforce.com';

    private static String SENSOR_ID = '110';
    private static String NONEXISTENT_ID = '404';

    private static String WRONG_SENSOR_EVENT_AMOUNT = 'Actual amount of sensor events does n\' equal to expected';
    private static String WRONG_SENSOR_AMOUNT = 'Actual amount of sensors does n\' equal to expected';

    @TestSetup
    static void makeData() {
        Account account = new Account(Name = 'Test');
        insert account;

        Sensor__c sensor = new Sensor__c(Name = SENSOR_ID,
                                         Account__c = account.Id);
        insert sensor;
    }

    @IsTest
    public static void checkWithExistSensor() {

        Account account = [SELECT Name FROM Account];

        List<Integer> line = new List<Integer>();
        for(Integer i = 0; i < 12; i++) {
            line.add(i);
        }
        SensorData sensorData = new SensorData(account.Id, SENSOR_ID, line);

        RestRequest request = new RestRequest();
        request.requestUri = SERVER_BASE_URL + '/services/apexrest/sensorEvent';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(JSON.serialize(sensorData));
        RestContext.request = request;

        SensorRestService.upsertData();

        List<Sensor__c> sensors = [SELECT Name FROM Sensor__c];
        System.assertEquals(1, sensors.size(), WRONG_SENSOR_EVENT_AMOUNT);

        List<Sensor_Event__c> events = [SELECT Name FROM Sensor_Event__c];

        System.assertEquals(line.size() / 3, events.size(), WRONG_SENSOR_EVENT_AMOUNT);
    }

    @IsTest
    public static void checkWithUnexistsSensor() {

        Account account = [SELECT Name FROM Account];

        List<Integer> line = new List<Integer>();
        for(Integer i = 0; i < 12; i++) {
            line.add(i);
        }
        SensorData sensorData = new SensorData(account.Id, NONEXISTENT_ID, line);

        RestRequest request = new RestRequest();
        request.requestUri = SERVER_BASE_URL + '/services/apexrest/sensorEvent';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(JSON.serialize(sensorData));
        RestContext.request = request;

        SensorRestService.upsertData();

        List<Sensor__c> sensors = [SELECT Name FROM Sensor__c];
        System.assertEquals(2, sensors.size(), WRONG_SENSOR_EVENT_AMOUNT);

        List<Sensor_Event__c> events = [SELECT Name FROM Sensor_Event__c];

        System.assertEquals(line.size() / 3, events.size(), WRONG_SENSOR_EVENT_AMOUNT);
    }

    @IsTest
    public static void checkWithUncorrectLine() {

        Account account = [SELECT Name FROM Account];

        List<Integer> line = new List<Integer>();
        for(Integer i = 0; i < 13; i++) {
            line.add(i);
        }
        SensorData sensorData = new SensorData(account.Id, SENSOR_ID, line);

        RestRequest request = new RestRequest();
        request.requestUri = SERVER_BASE_URL + '/services/apexrest/sensorEvent';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(JSON.serialize(sensorData));
        RestContext.request = request;

        SensorRestService.upsertData();

        List<Sensor_Event__c> events = [SELECT Name FROM Sensor_Event__c];

        System.assertEquals(line.size() / 3, events.size(), WRONG_SENSOR_EVENT_AMOUNT);
    }
}